---
title: "Untitled"
output: github_document
---

setwd("~/Documents/GitHub/Stats-133/labs4/lab14")

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}



library(dplyr)
library(tidyr)
library(stringr)
library(lubridate)
library(ggplot2)
library(ggrepel)

df = read.csv("EconomistData.csv")
View(df)

```




Make a basic plot
```{r}

ggplot(df) + geom_point(aes(x = CPI, y = HDI,color = Region), size = 1)

```

My second layer
```{r}

ggplot(df) + geom_smooth(aes(x = CPI, y = HDI), method = "lm", formula = y~log(x), se = FALSE,color="red") + geom_point(aes(x = CPI, y = HDI, color = Region), size = 1)

```

```{r}

ggplot(df) + geom_smooth(aes(x = CPI, y = HDI), method = "lm", formula = y~log(x), se = FALSE, color = "red") + geom_point(aes(x = CPI, y = HDI, color = Region), size = 1, shape = 1) 

```

The shaped aesthetic is a fixed value, and is not mapped from a variable. 

Finanling more aesthetics

```{r}

ggplot(df) + geom_smooth(aes(x = CPI, y = HDI), method = "lm", formula = y~log(x), se = FALSE, color = "red") + geom_point(aes(x = CPI, y = HDI, color = Region), size = 2, shape = 1, stroke = 1.5)

```

Adding the text

```{r}

ggplot(df) + geom_smooth(aes(x = CPI, y = HDI), method = "lm", formula = y~log(x), se = FALSE, color = "red") + geom_point(aes(x = CPI, y = HDI, color = Region), size = 1.5, shape = 1, stroke = 1.5) + geom_text(aes(x = CPI, y = HDI, label = Country), data = countriesnew, color = "gray20")



countryset = c("Singapore","New Zealand", "Norway" ,"Germany" ,"Japan", "Britain" ,"France", "United States","Barbados" ,"Congo" ,"Sudan" ,"Afghanistan" ,"Rwanda", "India" ,"Bhutan", "South Africa", "Botswana", "Cape Verde" ,"Myanamar", "Iraq", "China" ,"Brazil" ,"Argentina", "Russia", "Greece" ,"Italy", "Venezuela")
 
countriesnew

countriesnew = filter(df, Country %in% countryset)

```

Text White Space

```{r}


mod1 = ggplot(df) + geom_smooth(aes(x = CPI, y = HDI), method = "lm", formula = y~log(x),se = FALSE, color = "red") + geom_point(aes(x = CPI, y = HDI, color = Region), size = 1.5, shape = 1, stroke = 1.5) + geom_text_repel(aes(x = CPI, y = HDI, label = Country), data = countriesnew, color = "gray20") 

```

Modifying the legend


```{r}


```


```{r}

mod2 = mod1 + labs(x="Corruption Perceptions Index,2011 (10=least corrupt)",y="Human Development Index,2011 (1=Best)", title="Corruption and human development")



```

scales 

```{r}


mod3 = mod2 + scale_y_continuous(breaks=seq(0.2,1,0.1),limits=c(0.2,1)) + scale_x_continuous(breaks=1:10,limits=c(0.8,11))

```


color scheme

```{r}

mod3 + scale_color_manual(values=c("#24576D","#099DD7","#28AADC","#248E84","#F2583F","#96503F"))


```


```{r}


text = element_text(color = "gray20"),
legend.justification = 0.1, # anchor point for legend.position.
legend.text = element_text(size = 11, color = "gray10"),
axis.text = element_text(face = "italic"),
axis.title.x = element_text(vjust = -1), # move title away from axis
axis.title.y = element_text(vjust = 2), # move away for axis
axis.line = element_line(color = "gray40", size = 0.5),
panel.grid.major = element_line(color = "gray50", size = 0.5),
panel.grid.major.x = element_blank()


```

